name: Slack Poll Bot

# Ovaj workflow se može pokrenuti ručno
on:
  workflow_dispatch:

jobs:
  send-poll:
    runs-on: ubuntu-latest

    steps:
      # Kloniranje repozitorija
      - name: Checkout repository
        uses: actions/checkout@v3

      # Instaliranje Pythona
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Instaliranje zahtjeva (ako ih ima)
      - name: Install dependencies
        run: pip install requests

      # Pokretanje Python skripte
      - name: Run poll bot
        run: python app.py
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
