name: Slack Poll Bot

on:
  workflow_dispatch: # ručno pokretanje
  schedule:
    - cron: "0 7 * * *" # svaki dan u 07:00 (UTC)

jobs:
  send-poll:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Send Slack poll with buttons
        run: |
          python - <<'EOF'
          import os
          import requests

          SLACK_TOKEN = os.environ['SLACK_TOKEN']
          CHANNEL = "#general"

          payload = {
              "channel": CHANNEL,
              "text": "Are you working today?",  # fallback text
              "blocks": [
                  {
                      "type": "section",
                      "text": {"type": "mrkdwn", "text": "*Are you working today?*"}
                  },
                  {
                      "type": "actions",
                      "elements": [
                          {"type": "button", "text": {"type": "plain_text", "text": "Remote 🏠"}, "value": "remote"},
                          {"type": "button", "text": {"type": "plain_text", "text": "Office 🏢"}, "value": "office"},
                          {"type": "button", "text": {"type": "plain_text", "text": "Off 💤"}, "value": "off"}
                      ]
                  }
              ]
          }

          headers = {
              "Authorization": f"Bearer {SLACK_TOKEN}",
              "Content-Type": "application/json"
          }

          response = requests.post("https://slack.com/api/chat.postMessage", json=payload, headers=headers)
          print(response.json())
          EOF
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
