name: Slack Poll Bot

on:
  workflow_dispatch: # ručno pokretanje
  schedule:
    - cron: "0 7 * * *" # svaki dan u 07:00 (UTC)

jobs:
  send-poll:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Send Slack poll
        run: |
          python - <<'EOF'
          import os
          import requests

          SLACK_TOKEN = os.environ['SLACK_TOKEN']
          CHANNEL = "#general"

          def send_poll():
              text = '/poll "Are you working today?" "Remote" "Home" "Off - Not working"'
              headers = {
                  "Authorization": f"Bearer {SLACK_TOKEN}",
                  "Content-Type": "application/json"
              }
              payload = {
                  "channel": CHANNEL,
                  "text": text
              }
              response = requests.post("https://slack.com/api/chat.postMessage", json=payload, headers=headers)
              print(response.json())

          # Pokreće poll odmah kada se workflow starta
          send_poll()
          EOF
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
